---
title: "Problem Section 5"
subtitle:  "Confidence Intervals"
graphics: yes
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

* * * 
### Instructions

Please answer the following questions in the order in which they are posed. Add a few empty lines below each and write your answers there. Focus on answering in complete sentences. You will also need scratch paper/pen to work out the answers before typing it.

For help with formatting documents in RMarkdown, please consult [R Markdown: The Definitive Guide](https://bookdown.org/yihui/rmarkdown/). Another option is to search using Google. 

* * *

### Exercises 

1. In a grocery store, 400 customers shop everyday. The number of half-gallons of nonfat milk bought by a randomly selected customer is a random variable $X$ having PMF
\begin{align*}
f(x) &= \left\{ \begin{array}{cc}
                0.3 & x=0\\
                0.5 & x=1 \\
                0.2 & x=2 \end{array} \right.
\end{align*}

   Assume buying behaviors of different customers are independent. The grocer requests 390 half gallon containers per day from the distributor. Calculate, using the Central Limit Theorem,  the probability that, on a given day that is enough.  


2. Suppose $X_1, X_2, \dots, X_n$ are independently distributed with mean $\mu_0$ and variance $\sigma^2_0$.  Use Chebychev's inequality to come up with a confidence interval for $\mu_0$ which has at least 95% confidence.  

   Hint: For any random variable $X$ with mean $\mu$ and variance $\sigma^2$, Chebychev's inequality states that 
$$P(|X - \mu| \geq k \sigma) \leq \frac{1}{k^2}$$
  Apply Chebychev's inequality to the random variable $\bar{X}$.

3.  Suppose $X_1, X_2, \dots, X_n \overset{i.i.d.}{\sim} Unif(0, \theta_0)$.
Define
$$X_{max} = max \left\{X_1,X_2, \dots, X_n \right\}.$$
In this problem we will construct a 95\% confidence interval for $\theta_0$
using $X_{max}$ and its sampling distribution 
$$f_{X_{max}}(x) = \frac{n\:x^{n-1}}{\theta_0^n} \ \ 0 < x < \theta_0.$$ 

a. Let $q_{\alpha}$ denote the $\alpha$ quantile $f_{X_{max}}$. That is $q_{\alpha}$ is the number such that
$$P(X_{max} \leq q_{\alpha}) = \alpha.$$
Show that 
$$q_{\alpha} = \theta_0\: \alpha^{1/n}$$.

b. "Invert" the probability statement
$$P\left( q_{0.025} < X_{max} < q_{0.975} \right) = 0.95$$
to construct a 95% confidence interval for $\theta_0$. 

   Hint: this just means rearrange terms inside the probability so you move $\theta_0$ to the middle of the inequalities. 

c. Give an expression for the 95% confidence interval estimator for $\theta_0$.

d. Suppose our sample values are $x_1 = 0.2, x_2 = 0.9, x_3 = 1.9, x_4 = 2.2, x_5 = 4.7, x_6 = 5.1$. Calculate your interval for $\theta_0$ from part c. for this sample. 