---
title: "Problem Section 2"
date:  "Monday Jan 15 2024"
graphics: yes
output: pdf_document
header-includes:
    - \usepackage{amsmath, amssymb}
    - \usepackage{framed}\definecolor{shadecolor}{rgb}{0.949,0.949,0.949}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

\begin{shaded}

\textbf{Learning Outcomes}

The problems are designed to build conceptual understanding and problem-solving skills. The emphasis is on learning to find, evaluate and build confidence. The specific tasks include: 

 
   - Eyeballing if two random variables are independent of each other
   
   - Performing probability calculations with joint PDFs
   
   - Calculating the mean and standard deviation of linear combinations of independent random variables. 

   - Back up and support work with relevant explanations


\end{shaded}


* * *

### Exercises 

1. Suppose the probabilistic behavior of two random variables $X$ and $Y$ is defined by the joint density function:
$$f(x,y) = 2x +y - 2 x y \ \ \ 0 \leq x < 1 \ 0 \leq y < 1$$

a. Just by eyeballing, are $X$ and $Y$ independent? Why or why not?

b. Calculate $P(X < Y)$.

2. A mason is contracted to build a patio retaining wall. Plans call for the base of the wall to be a row of fifty 10-inch bricks, each separated by $\frac{1}{2}$ inch thick mortar. Suppose that the bricks used are randomly chosen from a
population of bricks whose mean length is 10 inches and
whose standard deviation is $\frac{1}{32}$ inch. Also, suppose that the
mason, on the average, will make the mortar $\frac{1}{2}$ inch thick,
but that the actual dimension will vary from brick to brick,
the standard deviation of the thicknesses being $\frac{1}{16}$ inch. What is the standard deviation of $L$, the length of the first
row of the wall? What assumption are you making?


3. Suppose $X$ and $Y$ are independent random variables, with $Var\left[X \right] = Var\left[Y \right] =1$. Consider the new random variable formed by the linear transformation $$W = c\:X + (1-c)\:Y.$$
Find the value of $c$  that minimizes the variance of $W$. 